version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    restart: unless-stopped

<<<<<<< HEAD
  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - "9093:9093"
    restart: unless-stopped
    depends_on:
      - prometheus

  telegram-bot:
    image: metalmatze/alertmanager-bot:0.4.3
    environment:
      - ALERTMANAGER_URL=http://alertmanager:9093
      - TELEGRAM_ADMIN=YOUR_TELEGRAM_USER_ID
      - TELEGRAM_TOKEN=YOUR_TELEGRAM_BOT_TOKEN
      - STORE=bolt
      - BOLT_PATH=/data/bot.db
      - TEMPLATE_PATHS=/templates/telegram.tmpl
    volumes:
      - ./alertmanager/templates:/templates
      - telegram_bot_data:/data
    ports:
      - "9087:8080"
    restart: unless-stopped
    depends_on:
      - alertmanager

=======
>>>>>>> 4a3fc5d84dbf914abe32c477ff49b4ebcca51881
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - prometheus
      - loki

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yaml
    volumes:
<<<<<<< HEAD
      - ./loki:/etc/loki
=======
      - /opt/ajx-monitoring/loki:/etc/loki
>>>>>>> 4a3fc5d84dbf914abe32c477ff49b4ebcca51881
      - loki_data:/loki
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    volumes:
<<<<<<< HEAD
      - ./promtail:/etc/promtail
      - /var/log:/var/log
      - ./promtail/targets:/etc/promtail/targets
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
=======
      - ./promtail/config.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
      - ./promtail/targets:/etc/promtail/targets
>>>>>>> 4a3fc5d84dbf914abe32c477ff49b4ebcca51881
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
<<<<<<< HEAD
  telegram_bot_data:
=======
>>>>>>> 4a3fc5d84dbf914abe32c477ff49b4ebcca51881
