global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # EC2 instances created by AJX-ENV-DEPTOOL with Node Exporter (Default Account)
  - job_name: 'node-exporter-default'
    ec2_sd_configs:
      - region: ap-southeast-1
        port: 9100
        # Default account: 533267407355
        filters:
          - name: "tag:CreatedBy"
            values: ["AJX-ENV-DEPTOOL"]
        refresh_interval: 30s
    relabel_configs:
      # Use public IP instead of private IP for scraping
      - source_labels: [__meta_ec2_public_ip]
        target_label: __address__
        replacement: '${1}:9100'
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
      - source_labels: [__meta_ec2_tag_Environment]
        target_label: environment
      - source_labels: [__meta_ec2_availability_zone]
        target_label: zone
      - source_labels: [__meta_ec2_instance_type]
        target_label: instance_type
      - source_labels: [__meta_ec2_private_ip]
        target_label: private_ip
      # Add a common job label for all node exporters
      - target_label: job
        replacement: 'node-exporter'

  # EC2 instances created by AJX-ENV-DEPTOOL with Node Exporter (Secondary Account)
  - job_name: 'node-exporter-secondary'
    ec2_sd_configs:
      - region: ap-southeast-1
        port: 9100
        # Secondary account: 925498464866
        role_arn: "arn:aws:iam::925498464866:role/prometheus-secondary-role"
        filters:
          - name: "tag:CreatedBy"
            values: ["AJX-ENV-DEPTOOL"]
        refresh_interval: 30s
    relabel_configs:
      # Use public IP instead of private IP for scraping
      - source_labels: [__meta_ec2_public_ip]
        target_label: __address__
        replacement: '${1}:9100'
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
      - source_labels: [__meta_ec2_tag_Environment]
        target_label: environment
      - source_labels: [__meta_ec2_availability_zone]
        target_label: zone
      - source_labels: [__meta_ec2_instance_type]
        target_label: instance_type
      - source_labels: [__meta_ec2_private_ip]
        target_label: private_ip
      # Add a common job label for all node exporters
      - target_label: job
        replacement: 'node-exporter'

  # PostgreSQL Exporter for DB instances (Default Account)
  - job_name: 'postgres-exporter-default'
    ec2_sd_configs:
      - region: ap-southeast-1
        port: 9187
        # Default account: 533267407355
        filters:
          - name: "tag:CreatedBy"
            values: ["AJX-ENV-DEPTOOL"]
          - name: "tag:Name"
            values: ["*DB*", "*db*", "*Db*", "*dB*"]
        refresh_interval: 30s
    relabel_configs:
      # Use public IP instead of private IP for scraping
      - source_labels: [__meta_ec2_public_ip]
        target_label: __address__
        replacement: '${1}:9187'
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
      - source_labels: [__meta_ec2_tag_Environment]
        target_label: environment
      # Add a common job label for all postgres exporters
      - target_label: job
        replacement: 'postgres-exporter'

  # PostgreSQL Exporter for DB instances (Secondary Account)
  - job_name: 'postgres-exporter-secondary'
    ec2_sd_configs:
      - region: ap-southeast-1
        port: 9187
        # Secondary account: 925498464866
        role_arn: "arn:aws:iam::925498464866:role/prometheus-secondary-role"
        filters:
          - name: "tag:CreatedBy"
            values: ["AJX-ENV-DEPTOOL"]
          - name: "tag:Name"
            values: ["*DB*", "*db*", "*Db*", "*dB*"]
        refresh_interval: 30s
    relabel_configs:
      # Use public IP instead of private IP for scraping
      - source_labels: [__meta_ec2_public_ip]
        target_label: __address__
        replacement: '${1}:9187'
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
      - source_labels: [__meta_ec2_tag_Environment]
        target_label: environment
      # Add a common job label for all postgres exporters
      - target_label: job
        replacement: 'postgres-exporter'

  # Linode servers with Node Exporter
  - job_name: 'linode-nodes'
    file_sd_configs:
      - files:
          - 'linode-targets.json'
        refresh_interval: 30s
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: cloud_provider
        replacement: linode

  # Linode PostgreSQL servers
  - job_name: 'linode-postgres'
    file_sd_configs:
      - files:
          - 'linode-postgres-targets.json'
        refresh_interval: 30s
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: cloud_provider
        replacement: linode