{
 "title": "PostgreSQL DB Monitoring",
 "tags": [
  "postgresql",
  "database"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(max_count_queries_calls, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Long Running Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top 10 Long Running Queries",
   "type": "table",
   "description": "Shows the top 10 longest running queries with their SQL statements",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "topk(10, pg_stat_activity_max_tx_duration{instance=~\".*-$environment-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Count Queries (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_count_queries_calls{instance=~\".*-$environment-.*\"}",
     "legendFormat": "{{instance}} - {{query}}"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "slow_queries_total_time", "legendFormat": "{{instance}} - {{query}}" }
   ]
  },
  {
   "title": "Total Query Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "total_query_time_total_exec_time",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}