{
 "title": "PostgreSQL Database",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "instance", "label": "Instance", "query": { "query": "query_result(pg_up)" } },
   { "name": "datname", "label": "Database", "query": "label_values(datname)" },
   {
    "name": "mode",
    "label": "Lock table",
    "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
   }
  ]
 },
 "panels": [
  { "title": "Issue Tracker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Slow Query",
   "type": "timeseries",
   "description": "Find the slow query texts with highest query mean time.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_stat_activity_current_queries_query_duration_seconds{instance=~\"$instance\"} > 0",
     "legendFormat": "{{instance}} - {{client_addr}} - {{usename}} - {{datname}} - {{query_part_1}}{{query_part_2}}{{query_part_3}}{{query_part_4}}{{query_part_5}}{{query_part_6}}{{query_part_7}}{{query_part_8}}{{query_part_9}}{{query_part_10}}{{query_part_11}}{{query_part_12}}{{query_part_13}}{{query_part_14}}{{query_part_15}}{{query_part_16}}{{query_part_17}}{{query_part_18}}{{query_part_19}}{{query_part_20}}{{query_part_21}}{{query_part_22}}{{query_part_23}}{{query_part_24}}{{query_part_25}}{{query_part_26}}{{query_part_27}}{{query_part_28}}{{query_part_29}}{{query_part_30}}{{query_part_31}}{{query_part_32}}{{query_part_33}}{{query_part_34}}{{query_part_35}}{{query_part_36}}{{query_part_37}}{{query_part_38}}{{query_part_39}}{{query_part_40}}{{query_part_41}}{{query_part_42}}{{query_part_43}}{{query_part_44}}{{query_part_45}}{{query_part_46}}{{query_part_47}}{{query_part_48}}{{query_part_49}}"
    }
   ]
  },
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_static{instance=\"$instance\"}",
       "legendFormat": "{{short_version}}"
      }
     ]
    },
    {
     "title": "Current fetch data",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 5, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Current insert data",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 10, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Current update data",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 15, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_connections{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Average CPU Usage",
     "type": "timeseries",
     "description": "Average user and system CPU time spent in seconds.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(process_cpu_seconds_total{instance=\"$instance\"}[5m]) * 1000)",
       "legendFormat": "CPU Time"
      }
     ]
    },
    {
     "title": "Average Memory Usage",
     "type": "timeseries",
     "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(rate(process_resident_memory_bytes{instance=\"$instance\"}[5m]))",
       "legendFormat": "Resident Mem"
      },
      {
       "expr": "avg(rate(process_virtual_memory_bytes{instance=\"$instance\"}[5m]))",
       "legendFormat": "Virtual Mem"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "description": "Number of open file descriptors",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_open_fds{instance=\"$instance\"}",
       "legendFormat": "Open FD"
      }
     ]
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shared Buffers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_shared_buffers_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Effective Cache",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_effective_cache_size_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Maintenance Work Mem",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_maintenance_work_mem_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Work Mem",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_work_mem_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max WAL Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_wal_size_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Random Page Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_random_page_cost{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Seq Page Cost",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_seq_page_cost{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max Worker Processes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_worker_processes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max Parallel Workers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_parallel_workers{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch data (SELECT)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Insert data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$instance\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Update data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Return data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_returned{datname=~\"$datname\", instance=~\"$instance\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Delete data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_deleted{datname=~\"$datname\", instance=~\"$instance\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Lock tables",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_locks_count{datname=~\"$datname\", instance=~\"$instance\", mode=~\"$mode\"} != 0",
       "legendFormat": "{{datname}},{{mode}}"
      }
     ]
    },
    {
     "title": "Conflicts/Deadlocks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(pg_stat_database_conflicts{instance=\"$instance\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} conflicts"
      },
      {
       "expr": "irate(pg_stat_database_deadlocks{instance=\"$instance\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} deadlocks"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(pg_stat_database_xact_commit{instance=\"$instance\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} commits"
      },
      {
       "expr": "irate(pg_stat_database_xact_rollback{instance=\"$instance\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} rollbacks"
      }
     ]
    },
    {
     "title": "Buffers (bgwriter)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend_total{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_backend"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_alloc_total{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_alloc"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync_total{instance=\"$instance\"}[5m])",
       "legendFormat": "backend_fsync"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_checkpoint_total{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_checkpoint"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_clean_total{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_clean"
      }
     ]
    },
    {
     "title": "Active sessions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state=\"active\"} !=0",
       "legendFormat": "{{datname}}, s: {{state}}"
      }
     ]
    },
    {
     "title": "Idle sessions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
       "legendFormat": "{{datname}}, s: {{state}}"
      }
     ]
    },
    {
     "title": "Temp File (Bytes)",
     "type": "timeseries",
     "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(pg_stat_database_temp_bytes{instance=\"$instance\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Cache Hit Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "pg_stat_database_blks_hit{instance=\"$instance\", datname=~\"$datname\"} / (pg_stat_database_blks_read{instance=\"$instance\", datname=~\"$datname\"} + pg_stat_database_blks_hit{instance=\"$instance\", datname=~\"$datname\"})",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "Checkpoint Stats",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_write_time_total{instance=\"$instance\"}[5m])",
       "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
      },
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time_total{instance=\"$instance\"}[5m])",
       "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
      }
     ]
    }
   ]
  },
  {
   "title": "Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgreSQL Database Activity",
     "type": "timeseries",
     "description": "Consolidated view of PostgreSQL metrics including I/O, tuple operations, transactions, and connections",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_blks_read{datname=~\"$datname\", instance=~\"$instance\"}[1m])",
       "legendFormat": "Disk Reads - {{datname}}"
      },
      {
       "expr": "rate(pg_stat_database_blks_hit{datname=~\"$datname\", instance=~\"$instance\"}[1m])",
       "legendFormat": "Buffer Hits - {{datname}}"
      },
      {
       "expr": "rate(pg_stat_database_blk_read_time{datname=~\"$datname\", instance=~\"$instance\"}[1m])",
       "legendFormat": "Read Time - {{datname}}"
      },
      {
       "expr": "rate(pg_stat_database_blk_write_time{datname=~\"$datname\", instance=~\"$instance\"}[1m])",
       "legendFormat": "Write Time - {{datname}}"
      },
      {
       "expr": "rate(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\"}[1m])",
       "legendFormat": "Tuples Fetched - {{datname}}"
      },
      {
       "expr": "rate(pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$instance\"}[1m])",
       "legendFormat": "Tuples Inserted - {{datname}}"
      },
      {
       "expr": "rate(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\"}[1m])",
       "legendFormat": "Tuples Updated - {{datname}}"
      },
      {
       "expr": "rate(pg_stat_database_tup_deleted{datname=~\"$datname\", instance=~\"$instance\"}[1m])",
       "legendFormat": "Tuples Deleted - {{datname}}"
      },
      {
       "expr": "rate(pg_stat_database_xact_commit{datname=~\"$datname\", instance=~\"$instance\"}[1m])",
       "legendFormat": "Transactions Committed - {{datname}}"
      },
      {
       "expr": "rate(pg_stat_database_xact_rollback{datname=~\"$datname\", instance=~\"$instance\"}[1m])",
       "legendFormat": "Transactions Rolled Back - {{datname}}"
      },
      {
       "expr": "pg_stat_database_numbackends{datname=~\"$datname\", instance=~\"$instance\"}",
       "legendFormat": "Active Connections - {{datname}}"
      }
     ]
    },
    {
     "title": "PostgreSQL Wait Events",
     "type": "timeseries",
     "description": "Shows the number of sessions waiting on specific events",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance, wait_event_type, wait_event) (pg_stat_activity_wait_events_count{instance=~\"$instance\"})",
       "legendFormat": "{{instance}} - {{wait_event_type}} - {{wait_event}}"
      }
     ]
    }
   ]
  }
 ]
}