server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Static Nginx logs configuration
  - job_name: nginx-local
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          source: local
          __path__: /var/log/nginx/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<remote_addr>\S+) - (?P<remote_user>\S+) \[(?P<time_local>[^\]]+)\] "(?P<method>\S+) (?P<request>\S+) (?P<protocol>\S+)" (?P<status>\d+) (?P<body_bytes_sent>\d+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"'
      - labels:
          method:
          status:
          request:
      - timestamp:
          source: time_local
          format: 02/Jan/2006:15:04:05 -0700
          
  # Auto-discovery for Nginx logs on other servers
  - job_name: nginx-discovery
    file_sd_configs:
      - files:
          - /etc/promtail/targets/*.yml
        refresh_interval: 5m
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__path__]
        target_label: __path__
    pipeline_stages:
      - regex:
          expression: '^(?P<remote_addr>\S+) - (?P<remote_user>\S+) \[(?P<time_local>[^\]]+)\] "(?P<method>\S+) (?P<request>\S+) (?P<protocol>\S+)" (?P<status>\d+) (?P<body_bytes_sent>\d+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"'
      - labels:
          method:
          status:
          request:
      - timestamp:
          source: time_local
          format: 02/Jan/2006:15:04:05 -0700